// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_3g_CgehkFH-Wp0BL2LH1SVoDXlSIn-E',
    appId: '1:859355606739:web:abfa0a666f241724932e26',
    messagingSenderId: '859355606739',
    projectId: 'techari-be4ba',
    authDomain: 'techari-be4ba.firebaseapp.com',
    storageBucket: 'techari-be4ba.firebasestorage.app',
    measurementId: 'G-NJYGLKFBTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZhcPg2stOOUWEblgmCQYnXu3IJ66hHlU',
    appId: '1:859355606739:android:afb850eda0b4ee6c932e26',
    messagingSenderId: '859355606739',
    projectId: 'techari-be4ba',
    storageBucket: 'techari-be4ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChv5zzBFUZ1ureU6PyhgZOSh6BuIB2DVU',
    appId: '1:859355606739:ios:f071d5504c6b23a6932e26',
    messagingSenderId: '859355606739',
    projectId: 'techari-be4ba',
    storageBucket: 'techari-be4ba.firebasestorage.app',
    iosClientId: '859355606739-rqr0m4tnbjcb4550ngnqvsp9es2jhh5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChv5zzBFUZ1ureU6PyhgZOSh6BuIB2DVU',
    appId: '1:859355606739:ios:f071d5504c6b23a6932e26',
    messagingSenderId: '859355606739',
    projectId: 'techari-be4ba',
    storageBucket: 'techari-be4ba.firebasestorage.app',
    iosClientId: '859355606739-rqr0m4tnbjcb4550ngnqvsp9es2jhh5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_3g_CgehkFH-Wp0BL2LH1SVoDXlSIn-E',
    appId: '1:859355606739:web:3a0dcb2191077691932e26',
    messagingSenderId: '859355606739',
    projectId: 'techari-be4ba',
    authDomain: 'techari-be4ba.firebaseapp.com',
    storageBucket: 'techari-be4ba.firebasestorage.app',
    measurementId: 'G-7447XYHQ3Q',
  );
}
