// Import the packages you'll need
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
// Import the file generated by FlutterFire
import 'firebase_options.dart';

// Your other imports for app screens...

void main() async { // 1. Add 'async'
  
  // 2. Ensure Flutter's engine is initialized
  WidgetsFlutterBinding.ensureInitialized();
  
  // 3. Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 4. Run your app (wrapping in ProviderScope for Riverpod)
  // runApp(const MyApp()); // This is the old line
  runApp(
    const ProviderScope( // Add this for Riverpod
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BookSwap',
      home: Text('Project Setup Complete!'), // Your app's home page
    );
  }
}